name: CI/CD for Alibaba Cloud Function

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Install Aliyun CLI
        run: |
          curl -s https://raw.githubusercontent.com/aliyun/aliyun-cli/master/install.sh | sudo bash
          aliyun version

      - name: Configure Aliyun CLI
        run: |
          mkdir -p ~/.aliyun
          aliyun configure set \
            --profile default \
            --mode AK \
            --region "${{ secrets.ALIYUN_REGION }}" \
            --access-key-id "${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_ID }}" \
            --access-key-secret "${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_SECRET }}"

      - name: Upload JAR to OSS
        run: |
          aliyun oss cp ./target/books-v1.0.jar oss://ci-cd-test/books-v1.0.jar --region "${{ secrets.ALIYUN_REGION }}" --force

      - name: List FC Functions
        run: |
          echo "===== Listing all functions ====="
          aliyun fc GET /2023-03-30/functions --region "${{ secrets.ALIYUN_REGION }}"
          echo "===== End of functions list ====="

      - name: Update Alibaba Cloud Function
        run: |
          aliyun fc PUT /2023-03-30/functions/ci_cd_test \
            --region "${{ secrets.ALIYUN_REGION }}" \
            --header "Content-Type=application/json" \
            --body "{\"code\":{\"ossBucketName\":\"ci-cd-test\",\"ossObjectName\":\"books-v1.0.jar\"}}"
