name: CI/CD for Alibaba Cloud Function

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Install Aliyun CLI
        run: |
          curl -o aliyun-cli.zip https://aliyuncli.alicdn.com/aliyun-cli-linux-amd64.zip
          unzip aliyun-cli.zip
          sudo mv aliyun /usr/local/bin/
          rm aliyun-cli.zip

      - name: Configure Aliyun CLI
        run: |
          mkdir -p ~/.aliyun
          echo "[default]" > ~/.aliyun/credentials
          echo "access_key_id=${{ secrets.ALIYUN_ACCESS_KEY_ID }}" >> ~/.aliyun/credentials
          echo "access_key_secret=${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}" >> ~/.aliyun/credentials

      - name: Upload JAR to OSS
        run: |
          aliyun oss cp ./target/books-v1.0.jar oss://ci-cd-test/books-v1.0.jar

      - name: Update Alibaba Cloud Function
        run: |
          aliyun fc update-function --function-name ci_cd_test --code oss://ci-cd-test/books-v1.0.jar
